title: aaron.codes
email: hire@aaron.codes
description: >-
  I'm an experienced full stack developer from the UK,
  specialising in Laravel and Vue.
baseurl: ""
url: "https://aaron.codes"
email: hire@aaron.codes
twitter_username: _aaronlord
github_username:  aaronlord
coding_since: 2010

excerpt_separator: <!-- excerpt -->
permalink: /:title
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-purgecss

exclude:
  - css/tailwind.css
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
