title      : aaron.codes
email      : hire@aaron.codes
description: >
  I'm a talented back-to-front-end web developer, based in the UK. I've got a great
  deal to offer and I'm extremely passionate about our work. Get in touch and we'll
  build something beautiful.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aaron.codes" # the base hostname & protocol for your site, e.g. http://example.com

gplus_username: +aaronlords
twitter_username: _aaronlord
github_username :  aaronlord
bitbucket_username: aaronlord

# Build settings
markdown: kramdown
permalink: /:title

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

adam_dribbble_username: kralcmada
coding_since: 2007;

sass:
    style: compressed
