title: aaron.codes
email: hire@aaron.codes
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://aaron.codes"
email: hire@aaron.codes
twitter_username: _aaronlord
github_username:  aaronlord

excerpt_separator: <!-- excerpt -->
permalink: /:title
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-purgecss

exclude:
  - css/tailwind.css
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
